language: php

php:
  - 7.2

before_install:
  - composer require php-coveralls/php-coveralls '~1.0'
  - composer install --dev
  - git clone https://github.com/gamcoh/Gamzer-PHP-Standard.git ./vendor/squizlabs/php_codesniffer/src/Standards/
  - ./vendor/bin/phpcs --config-set installed_path ./vendor/squizlabs/php_codesniffer/src/Standards/,./vendor/squizlabs/php_codesniffer/src/Standards/Gamzer-PHP-Standard/Gamzer,./vendor/squizlabs/php_codesniffer/src/Standards/Gamzer-PHP-Standard/Gamzerpear

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
  - ./vendor/bin/phpcs ./

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true

notifications:
  on_success: always
  on_failure: always
