language: php

php:
  - 7.2

before_install:
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - composer require php-coveralls/php-coveralls '^2.1'
  - composer install
  - git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git /tmp/phpcs
  - git clone -b master https://github.com/gamcoh/Gamzer-PHP-Standard.git /tmp/Gamzer-PHP-Standard
  - /tmp/phpcs/bin/phpcs --config-set installed_paths /tmp/Gamzer-PHP-Standard/

before_script:
  - mkdir -p tests/logs

script:
  - ./vendor/bin/phpunit -c ./ --coverage-text --coverage-clover tests/logs/clover.xml
  - /tmp/phpcs/bin/phpcs . --standard=./phpcs.xml

after_script:
  - ls -lah ./vendor/bin/
  - php ./vendor/bin/php-coveralls -v

matrix:
  fast_finish: true

notifications:
  on_success: always
  on_failure: always

