language: php

php:
  - 7.2

before_install:
  - composer require php-coveralls/php-coveralls '~1.0'
  - composer install --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true

notifications:
  on_success: always
  on_failure: always
